[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
k_3_hoot_program_arcium = "BbjmhBTQNnXBqEAFCPmRk5qBpTfdmu8Vb2evMVvAcxCm"

[programs.localnet]
k_3_hoot_program_arcium = "BbjmhBTQNnXBqEAFCPmRk5qBpTfdmu8Vb2evMVvAcxCm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
